### ISSUE TITLE
[DOC] Broken links in readme (JOSS Review)

### ISSUE THREAD

**Issue by roth-jakob** [jeertmans/DiffeRT2d#67]
Some links in the README are broken. When I click "Contributing guide" and "examples", I get a 404 Not Found message.

Ref: openjournals/joss-reviews#6915

**Comment by jeertmans** [comment]
Hello @roth-jakob, thanks for catching those!

Keeping track of all links isn't always easy, even with automated tests (see #68).
I have fixed the broken links (I did a typo by adding `latest/` to the wrong link), but I am still thinking a bit how to fix other false positive errors reported by `markdown-link-check`.

**Comment by roth-jakob** [comment]
Hi, thanks for fixing the links! Looks good to me.
